// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package sqlcCode

import ()

type Topstory struct {
	StoryID   int64
	Title     string
	Score     int64
	Url       string
	Timestamp string
}
