// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package sqlcCode

import ()

type Topstory struct {
	StoryID   int32
	Title     string
	Score     string
	Url       string
	Timestamp string
}
